### PR TITLE
Create directory hierarchy for C compilation

### LINKED ISSUE #9: GHC cannot create output dir tree
```
mkdir tmp
ghc -c csrc/code.c -outputdir tmp/
# This works fine, creates tmp/csrc/code.o
wasm32-unknown-unknown-wasm-ghc -c csrc/code.c -outputdir tmp/
error: unable to open output file 'tmp/csrc/code.o': 'No such file or directory'
```
Due to this cannot compile cabal projects with c-sources.

### PR DESCRIPTION
**Pull request by dfordivam**
Fixes #9

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
Is this specific to WebGHC in any way or does the problem also occur with native GHC? If it's not specific to WebGHC, I'd argue this patch should be submitted upstream instead of here. Then we can just merge in master.

**Comment by dfordivam** [comment]
Actually I am not sure.
I could not reproduce it in native ghc; perhaps because its compilation pipeline is different...

**Comment by ElvishJerricco** [comment]
@dfordivam Ah, yea we actually had to explicitly disable the pipeline phase that goes through assembly (`$CC -S`) because Clang / LLVM don't yet have a functioning assembly language for wasm object files. Maybe this is the phase in the pipeline where the directory is usually made? We can test by just seeing if upstream native GHC has this problem with the via-C backend.

**Comment by ElvishJerricco** [comment]
I'll merge this for now, but this is one of the things we're going to have to come back to before we start to upstream anything.

**Pull request merged**
